# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        
        #run_btn按鈕設定
        self.run_btn = QtWidgets.QPushButton(self.centralwidget)
        self.run_btn.setMinimumSize(QtCore.QSize(70, 70))
        self.run_btn.setMaximumSize(QtCore.QSize(150,100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.run_btn.setFont(font)
        self.run_btn.setObjectName("run_btn")
        self.verticalLayout.addWidget(self.run_btn)

        #stop_btn按鈕設定
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setMinimumSize(QtCore.QSize(70, 70))
        self.stop_btn.setMaximumSize(QtCore.QSize(150,100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout.addWidget(self.stop_btn)

        
        self.horizontalLayout.addLayout(self.verticalLayout)

        #圖片顯示設定
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(1080,720))
        self.graphicsView.setMaximumSize(QtCore.QSize(2560,1440))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.scene = QtWidgets.QGraphicsScene()
        self.graphicsView.setScene(self.scene)

        #圖片顯示設定
        self.pixmap_item = QGraphicsPixmapItem() 
        self.scene.addItem(self.pixmap_item) 

        #menu設定
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1139, 25))
        self.menubar.setMinimumSize(QtCore.QSize(200, 0))
        self.menubar.setObjectName("menubar")

        #help設定
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setEnabled(True)
        self.menuhelp.setGeometry(QtCore.QRect(270, 151, 200, 135))
        self.menuhelp.setMinimumSize(QtCore.QSize(200, 20))
        self.menuhelp.setObjectName("menuhelp")
        self.menuhelp.size

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.action_system_info=QAction(QIcon('icons/resetall.png'), 'system info...', MainWindow)
        self.action_system_info.setShortcut('Ctrl+Shift+I')
        self.action_system_info.setStatusTip('show system info')
        font = QtGui.QFont()
        font.setPointSize(11)
        self.action_system_info.setFont(font)
        self.action_system_info.setObjectName("actionsysteminfo")

        self.action_cuda_info=QAction(QIcon('icons/help.png'), 'check cuda...', MainWindow)
        self.action_cuda_info.setShortcut('Ctrl+Shift+C')
        self.action_cuda_info.setStatusTip('show cuda info')
        font = QtGui.QFont()
        font.setPointSize(11)
        self.action_cuda_info.setFont(font)
        self.action_cuda_info.setObjectName("actionmodelinfo")

        #按鈕連接
        self.menuhelp.addAction(self.action_system_info)
        self.menuhelp.addAction(self.action_cuda_info)

        #按鈕連接
        self.menubar.addAction(self.menuhelp.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BAOCH山老鼠偵測"))
        self.run_btn.setText(_translate("MainWindow", "RUN"))
        self.stop_btn.setText(_translate("MainWindow", "STOP"))
        self.menuhelp.setTitle(_translate("MainWindow", "Help"))

    def closeEvent(self, event):
        reply = QMessageBox.question(self, 'Message', 'Are you sure to quit?', QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if reply == QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
